# Generated by Django 4.2.24 on 2025-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ball', 'Ball'), ('jersey', 'Jersey'), ('boots', 'Boots'), ('accecories', 'Accecories'), ('medicine', 'Medicine'), ('analysis', 'Analysis')], default='ball', max_length=20),
        ),
    ]
