# Generated by Django 4.2.24 on 2025-09-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_content_product_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
    ]
